# compiling ebola data

The DATA_FOLDER/ebola folder contains summarized reports of Ebola cases from three countries (Guinea, Liberia and Sierra Leone) during the recent outbreak of the disease in West Africa. For each country, there are daily reports that contain various information about the outbreak in several cities in each country.
Use pandas to import these data files into a single Dataframe. Using this DataFrame, calculate for each country, the daily average per month of new cases and deaths. Make sure you handle all the different expressions for new cases and deaths that are used in the reports.

In [42]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

At first we want to see how it looks like one csv for each country.

In [43]:
guinea_first = pd.read_csv("Data/ebola/guinea_data/2014-08-04.csv")
guinea_first

,Date,Description,Totals,Conakry,Gueckedou,Macenta,Dabola,Kissidougou,Dinguiraye,Telimele,Boffa,Kouroussa,Dubreka,Siguiri,Pita,Nzerekore
0,2014-08-04,New cases of suspects,5,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2014-08-04,New cases of probables,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2014-08-04,New cases of confirmed,4,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2014-08-04,Total new cases registered so far,9,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2014-08-04,Total cases of suspects,11,9.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2014-08-04,Total cases of probables,133,8.0,95.0,11.0,3.0,4.0,1.0,3.0,5.0,2.0,0.0,0.0,1.0,0.0
6,2014-08-04,Total cases of confirmed,351,78.0,188.0,28.0,1.0,2.0,0.0,23.0,18.0,2.0,0.0,6.0,1.0,4.0
7,2014-08-04,Cumulative (confirmed + probable + suspects),495,95.0,285.0,39.0,4.0,6.0,1.0,26.0,23.0,4.0,0.0,6.0,2.0,4.0
8,2014-08-04,New deaths registered today,2,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2014-08-04,New deaths registered today (confirmed),2,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2014-08-04,New deaths registered today (probables),0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2014-08-04,New deaths registered today (suspects),0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2014-08-04,Total deaths of suspects,2,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2014-08-04,Total deaths of probables,133,8.0,95.0,11.0,3.0,4.0,1.0,3.0,5.0,2.0,0.0,0.0,1.0,0.0
14,2014-08-04,Total deaths of confirmed,228,32.0,152.0,18.0,1.0,1.0,0.0,7.0,11.0,1.0,0.0,3.0,1.0,1.0
15,2014-08-04,Total deaths (confirmed + probables + suspects),363,42.0,247.0,29.0,4.0,5.0,1.0,10.0,16.0,3.0,0.0,3.0,2.0,1.0
16,2014-08-04,Total PEC center today,31,21.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
17,2014-08-04,Total PEC center today (confirmed),18,10.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
18,2014-08-04,Total PEC center today (probables),0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2014-08-04,Total PEC center today (suspects),13,11.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2014-08-04,Total of deaths in confirmed cases in CTE,138,20.0,95.0,10.0,0.0,1.0,0.0,5.0,6.0,0.0,0.0,2.0,0.0,0.0
21,2014-08-04,Total of cured in confirmed cases in CTE,89,34.0,30.0,8.0,0.0,1.0,0.0,9.0,7.0,0.0,0.0,0.0,0.0,0.0
22,2014-08-04,Number of male confirmed cases,161,48.0,72.0,14.0,1.0,1.0,0.0,6.0,10.0,1.0,0.0,6.0,0.0,2.0
23,2014-08-04,Number of female confirmed cases,190,30.0,116.0,14.0,0.0,1.0,0.0,17.0,8.0,1.0,0.0,0.0,1.0,2.0
24,2014-08-04,Number of male probables cases,52,4.0,34.0,5.0,1.0,1.0,0.0,1.0,3.0,2.0,0.0,0.0,1.0,0.0
25,2014-08-04,Number of female probables cases,81,4.0,61.0,6.0,2.0,3.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0
26,2014-08-04,Number of male suspects cases,7,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
27,2014-08-04,Number of female suspects cases,6,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2014-08-04,Total number of male cases,220,57.0,106.0,19.0,2.0,2.0,0.0,7.0,13.0,3.0,0.0,8.0,1.0,2.0
29,2014-08-04,Total number of female cases,277,38.0,179.0,20.0,2.0,4.0,1.0,19.0,10.0,1.0,0.0,0.0,1.0,2.0
30,2014-08-04,Number of confirmed cases among health workers,21,16.0,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0
31,2014-08-04,Number of deaths of confirmed cases among heal...,12,10.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,2014-08-04,Number of probables cases among health workers,8,1.0,4.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
33,2014-08-04,Number of deaths of probables cases among heal...,8,1.0,4.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
34,2014-08-04,Number of suspects cases among health workers,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
35,2014-08-04,Number of death of confirmed cases among healt...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,2014-08-04,Total contacts registered from start date,6309,1592.0,3049.0,430.0,69.0,158.0,0.0,259.0,397.0,53.0,118.0,141.0,41.0,69.0
37,2014-08-04,Number of contacts to follow today,795,350.0,201.0,46.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,135.0,26.0,69.0
38,2014-08-04,Number of contacts out of track,5513,1242.0,2848.0,384.0,69.0,159.0,0.0,259.0,397.0,16.0,118.0,6.0,15.0,0.0
39,2014-08-04,Number of contacts followed yesterday,772,331.0,200.0,44.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,134.0,26.0,0.0
40,2014-08-04,Number of patients tested,785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2014-08-04,Number of samples collected,1235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
liberia_first = pd.read_csv("Data/ebola/liberia_data/2014-06-16.csv")
liberia_first

,Date,Variable,National,Bomi County,Bong County,Grand Kru,Lofa County,Margibi County,Maryland County,Montserrado County,Nimba County,River Gee County,RiverCess County,Sinoe County
0,6/16/2014,Specimens collected,1.0,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1,6/16/2014,Specimens pending for testing,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,6/16/2014,Total specimens tested,28.0,NaN,NaN,NaN,21.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN
3,6/16/2014,Newly reported deaths,2.0,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,6/16/2014,Total death/s in confirmed cases,8.0,NaN,NaN,NaN,4.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
5,6/16/2014,Total death/s in probable cases,6.0,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
6,6/16/2014,Total death/s in suspected cases,2.0,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
7,6/16/2014,"Total death/s in confirmed, probable, suspecte...",16.0,NaN,NaN,NaN,8.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
8,6/16/2014,Case Fatality Rate (CFR) - Confirmed & Probabl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,6/16/2014,Newly reported contacts,41.0,NaN,NaN,NaN,41.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
10,6/16/2014,Total contacts listed,108.0,NaN,NaN,NaN,95.0,NaN,NaN,13.0,NaN,NaN,NaN,NaN
11,6/16/2014,Currently under follow-up,95.0,NaN,NaN,NaN,95.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
12,6/16/2014,Contacts seen,95.0,NaN,NaN,NaN,95.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
13,6/16/2014,Contacts who completed 21 day follow-up,11.0,NaN,NaN,NaN,11.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
14,6/16/2014,Contacts lost to follow-up,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
15,6/16/2014,New admissions,1.0,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
16,6/16/2014,Total no. currently in Treatment Units,5.0,NaN,NaN,NaN,5.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
17,6/16/2014,Total discharges,3.0,NaN,NaN,NaN,3.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
18,6/16/2014,Cumulative admission/isolation,5.0,NaN,NaN,NaN,5.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
19,6/16/2014,Newly Reported Cases in HCW,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,6/16/2014,Cumulative cases among HCW,1.0,NaN,NaN,NaN,0.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
21,6/16/2014,Newly Reported deaths in HCW,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
22,6/16/2014,Cumulative deaths among HCW,1.0,NaN,NaN,NaN,0.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
23,6/16/2014,New Case/s (Suspected),2.0,NaN,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
24,6/16/2014,New Case/s (Probable),1.0,NaN,NaN,NaN,0.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
25,6/16/2014,New case/s (confirmed),1.0,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
26,6/16/2014,Total suspected cases,4.0,NaN,NaN,NaN,4.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
27,6/16/2014,Total probable cases,6.0,NaN,NaN,NaN,2.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN
28,6/16/2014,Total confirmed cases,12.0,NaN,NaN,NaN,8.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN
29,6/16/2014,Total Number of Confirmed Cases of Sierra Leon...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN
30,6/16/2014,Total Number of Confirmed Cases of Guinean Nat...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
sl_first = pd.read_csv("Data/ebola/sl_data/2014-08-12-v77.csv")
sl_first

,date,variable,Kailahun,Kenema,Kono,Kambia,Koinadugu,Bombali,Tonkolili,Port Loko,Pujehun,Bo,Moyamba,Bonthe,Western area urban,Western area rural,National
0,2014-08-12,population,465048,653013,325003.0,341690.0,335471.0,494139,434937,557978,335574,654142,278119,168729.0,1040888,263619,6348350
1,2014-08-12,new_noncase,0,3,0.0,0.0,0.0,0,0,1,0,0,0,0.0,0,0,4
2,2014-08-12,new_suspected,0,9,0.0,0.0,0.0,0,0,0,0,1,0,0.0,0,0,10
3,2014-08-12,new_probable,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0.0,0,0,1
4,2014-08-12,new_confirmed,0,9,0.0,0.0,0.0,0,0,2,0,0,0,0.0,0,0,11
5,2014-08-12,cum_noncase,201,269,15.0,1.0,15.0,10,10,7,2,54,12,0.0,56,5,657
6,2014-08-12,cum_suspected,0,10,33.0,0.0,0.0,1,0,0,0,2,0,0.0,0,0,46
7,2014-08-12,cum_probable,32,0,1.0,0.0,0.0,1,0,1,0,1,0,0.0,1,0,37
8,2014-08-12,cum_confirmed,378,259,1.0,1.0,0.0,7,2,24,3,22,5,1.0,13,1,717
9,2014-08-12,death_suspected,2,1,0.0,0.0,0.0,0,0,1,0,0,0,0.0,1,0,5
10,2014-08-12,death_probable,32,0,0.0,0.0,0.0,0,0,1,0,0,0,0.0,1,0,34
11,2014-08-12,death_confirmed,151,104,0.0,0.0,0.0,1,0,1,0,2,3,0.0,2,0,264
12,2014-08-12,cfr,39.9,40.2,0.0,0.0,0.0,14.3,0,4.2,0,9.1,60,0.0,15.4,0,36.8
13,2014-08-12,etc_new_admission,16,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2014-08-12,etc_currently_admitted,53,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2014-08-12,etc_cum_admission,341,303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2014-08-12,etc_new_deaths,5,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2014-08-12,etc_cum_deaths,104,154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2014-08-12,etc_new_discharges,7,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2014-08-12,etc_cum_discharges,134,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2014-08-12,cum_contacts,NaN,"1,356",38.0,0.0,0.0,161,16,471,57,227,73,26.0,390,23,2838
21,2014-08-12,cum_completed_contacts,NaN,701,38.0,0.0,0.0,16,0,7,10,67,0,26.0,82,0,901
22,2014-08-12,contacts_followed,321,497,0.0,0.0,0.0,161,11,466,47,160,73,0.0,310,23,2255
23,2014-08-12,new_contacts,321,73,0.0,0.0,0.0,5,5,308,0,6,0,0.0,25,0,743
24,2014-08-12,contacts_healthy,305,427,0.0,0.0,0.0,141,11,443,47,157,73,0.0,103,23,1937
25,2014-08-12,contacts_ill,11,3,0.0,0.0,0.0,0,0,0,0,0,0,0.0,0,0,14
26,2014-08-12,contacts_not_seen,16,64,0.0,0.0,0.0,20,0,28,0,3,0,0.0,0,0,131
27,2014-08-12,new_completed_contacts,12,38,0.0,0.0,0.0,16,0,0,1,0,0,0.0,6,0,73
28,2014-08-12,percent_seen,98%,61%,NaN,NaN,NaN,97%,100%,95%,100%,98%,100%,NaN,101%,100%,87%

In [46]:
# Create 3 dataframes
dfs = [pd.DataFrame(columns=['country','new cases','new deaths']) for i in range(3)]

In [53]:
# Read Guinea data

import os

guinea_dir = "Data/ebola/guinea_data/"
guinea_df = dfs[0]
for file in os.listdir(guinea_dir):
    daily = pd.read_csv(guinea_dir + file, parse_dates=['Date'])
    date = daily.Date[0]
    new_deaths = daily[(daily.Description=='New deaths registered') | (daily.Description=='New deaths registered today')]
    new_deaths.index = new_deaths.Date
    new_deaths_count = int(new_deaths.loc[date,'Totals'])
    new_cases = daily[daily.Description=='New cases of confirmed']
    new_cases.index = new_cases.Date
    new_cases_count = int(new_cases.loc[date,'Totals'])
    guinea_df.loc[date] = ['Guinea',new_cases_count, new_deaths_count]
    
guinea_df.head()

           country new cases new deaths
date
2014-08-04  Guinea         4          2
2014-08-26  Guinea        10          5
2014-08-27  Guinea        10          2
2014-08-30  Guinea         9          5
2014-08-31  Guinea        29          3

In [48]:
# Read Liberia data

liberia_dir = "Data/ebola/liberia_data/"
liberia_df = dfs[1]
for file in os.listdir(liberia_dir):
    daily = pd.read_csv(liberia_dir + file, parse_dates=['Date']).fillna(0) 
    date = daily.Date[0]
    daily.index = daily.Variable
    new_deaths_count = int(daily.loc['Newly reported deaths','National'])
    new_cases_count = int(daily.loc['New case/s (confirmed)','National'])
    liberia_df.loc[date] = ['Liberia', new_cases_count, new_deaths_count]

In [49]:
# Read Sierra Leone data

sl_dir = "Data/ebola/sl_data/"
sl_df = dfs[2]
for file in os.listdir(sl_dir):
    daily = pd.read_csv(sl_dir + file, parse_dates=['date']).fillna(0)
    date = daily.date[0]
    daily.index = daily.variable
    new_cases_count = int(daily.loc['new_confirmed', 'National'])
    new_deaths_count = int(daily.loc['etc_new_deaths', 'National'])
    sl_df.loc[date] = ['Sierra Leone',new_cases_count, new_deaths_count]

In [62]:
# Create new dataframes with hierarchical index
new_df = []
for df in dfs:
    df.index.name = 'date'
    new_df.append(df.set_index(['country', df.index]))

# Concatenate the dataframes row-wise
final_df = pd.concat(new_df, axis=0)
final_df

                        new cases new deaths
country      date
Guinea       2014-08-04         4          2
             2014-08-26        10          5
             2014-08-27        10          2
             2014-08-30         9          5
             2014-08-31        29          3
             2014-09-02        14          5
             2014-09-04        17          5
             2014-09-07        11          4
             2014-09-08        11          4
             2014-09-09         7          7
             2014-09-11        13          2
             2014-09-14        14          1
             2014-09-16         6          3
             2014-09-17         6          3
             2014-09-19        12          5
             2014-09-21        17          0
             2014-09-22        14          3
             2014-09-23        25          3
             2014-09-24        20          3
             2014-09-26        10          5
             2014-09-30        11          4
             2014-10-01         6         15
Liberia      2014-06-16         1          2
             2014-06-17         0          0
             2014-06-22         5          4
             2014-06-24         4          4
             2014-06-25         2          3
             2014-06-28         1          1
             2014-06-29         2          0
             2014-07-01         2          5
...                           ...        ...
Sierra Leone 2014-10-27        91          0
             2014-10-28        47          0
             2014-10-30        50          8
             2014-10-31        95          3
             2014-11-01        60          1
             2014-11-02        61          4
             2014-11-06        41          3
             2014-11-07        45          3
             2014-11-08       111          1
             2014-11-10        94          0
             2014-11-12        61          0
             2014-11-13        84          0
             2014-11-14         0          0
             2014-11-15        54          0
             2014-11-16        89          0
             2014-11-17        53          0
             2014-11-18        43          0
             2014-11-19         0          0
             2014-11-20        94          0
             2014-11-21        51          0
             2014-11-22        47          0
             2014-11-23        39          0
             2014-11-24        83          0
             2014-11-28        84          0
             2014-11-29        64          0
             2014-12-01        72          0
             2014-12-04        37          3
             2014-12-05        54          8
             2014-12-06         0          0
             2014-12-13         0          0

[225 rows x 2 columns]

At this point we compute the daily average per month of new cases and deaths for each country.

In [79]:
final_Guinea = final_df.loc['Guinea']
final_Guinea.loc['2014-08-04':'2014-08-31'].mean()

# how to generalise this?

new cases     12.4
new deaths     3.4
dtype: float64